name: Main
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: step 1
      uses: actions/checkout@v3
    - name: step 2
      uses: actions/setup-node@v2
      with:
        node version: "14.x"
    - name: instalacja dependencji
      run: npm install
    - name: uruchomienie testow
      run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: step 1
      uses: actions/checkout@v3
    - name: step 2
      uses: azure/appservice-build@v3
      with:
        platform: nodejs
        platform-version: 14.21.3
    - name: Deploy App to Azure App Service
      uses: azure/webapps-deploy@v1
      with:
        app-name: aplikacja-nowa1
        publish-profile: ${{secrets.AZURE_WEB_APP_PUBLISH_PROFILE}}
